services:
  marketplace-gateway:
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: always
    image: marketplace-gateway
    container_name: marketplace-gateway
    volumes:
      - /home/kinoko/logs/marketplace-gateway:/logs
    #      - ./logs:/logs                             # Для отладки на windows машине
    networks:
      - backend
    ports:
      - "33306:33306"

networks:
  backend:
    external: true
